[package]
name = "herbolution-client"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam.workspace = true
engine = { package = "herbolution-engine", path = "../engine" }
game = { package = "herbolution-game", path = "../game" }
lib = { package = "herbolution-lib", path = "../lib" }
math = { package = "herbolution-math", path = "../math" }
num.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
winit.workspace = true
