[package]
name = "herbolution-game"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck.workspace = true
cached.workspace = true
generational-arena.workspace = true
hashbrown.workspace = true
lib = { package = "herbolution-lib", path = "../lib" }
math = { package = "herbolution-math", path = "../math" }
simdnoise.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }