[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.95"
bincode = "1.3.3"
bitflags = "2.8.0"
bytemuck = { version = "1.21.0", features = ["derive"] }
futures = "0.3.31"
glam = { version = "0.29.2", features = ["bytemuck", "serde"] }
glyphon = "0.7.0"
hashbrown = "0.15.2"
homedir = "0.3.4"
image = "0.25.5"
pollster = "0.4.0"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
simdnoise = "3.1.6"
thiserror = "2.0.11"
time = { version = "0.3.37", features = ["serde"] }
tokio = { version = "1.43.0", features = ["macros", "net", "rt-multi-thread", "sync"] }
toml = "0.8.19"
wgpu = "23.0.1"
winit = "0.30.8"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"