[package]
name = "herbolution"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["lib", "math", "math/derive"]

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
herbolution-lib = { path = "lib" }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.19"