[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
bitflags = "2.9.0"
bytemuck = "1.22.0"
cached = "0.55.1"
clap = "4.5.18"
crossbeam = "0.8.4"
futures = "0.3.31"
glyphon = "0.9.0"
hashbrown = "0.15.2"
image = "0.25.5"
image-atlas = "0.4.1"
lazy_static = "1.5.0"
line_drawing = "1.0.1"
num = "0.4.3"
oneshot = "0.1.11"
pollster = "0.4.0"
pulz-arena = "0.4.0"
rayon = "1.10.0"
serde = "1.0.219"
simdnoise = "3.1.6"
smallvec = "1.14.0"
thiserror = "2.0.12"
tokio = "1.44.0"
toml = "0.8.20"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
wgpu = "25.0.0"
winit = "0.30.9"
generational-arena = "0.2.9"
bimap = "0.6.3"