[workspace]
resolver = "2"
members = ["client", "engine", "game", "lib", "math"]

[workspace.dependencies]
bitflags = "2.9.0"
bytemuck = "1.22.0"
cached = "0.55.1"
glyphon = "0.8.0"
hashbrown = "0.15.2"
image = "0.25.5"
image-atlas = "0.4.1"
lazy_static = "1.5.0"
num = "0.4.3"
pollster = "0.4.0"
pulz-arena = "0.4.0"
serde = "1.0.219"
simdnoise = "3.1.6"
smallvec = "1.14.0"
thiserror = "2.0.12"
tokio = "1.44.0"
wgpu = "24.0.1"
winit = "0.30.9"