[workspace]
resolver = "2"
members = ["client", "engine", "game", "lib", "math"]

[workspace.dependencies]
bytemuck = "1.22.0"
cached = "0.55.1"
generational-arena = "0.2.9"
hashbrown = "0.15.2"
image = "0.25.5"
num = "0.4.3"
pollster = "0.4.0"
serde = "1.0.218"
simdnoise = "3.1.6"
smallvec = "1.14.0"
thiserror = "2.0.12"
tokio = "1.44.0"
winit = "0.30.9"