[package]
name = "herbolution-math-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
case = "1.0.0"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full"] }