name: Rust CI

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            architecture: x86_64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            architecture: arm64
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            architecture: x86_64
            target: x86_64-apple-darwin
          - os: macos-latest
            architecture: arm64
            target: aarch64-apple-darwin
          - os: windows-latest
            architecture: x86_64
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            architecture: arm64
            target: aarch64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --verbose --target ${{ matrix.target }}

      - name: Run tests
        run: cargo test --verbose --target ${{ matrix.target }}
